function [Category_Error_Rate,Category_Accuracy_Rate]= KNN_Test()
MFile=load('knnmodels');
File=load('Sound');
%==================Sound KNN test======================================%
[Category1,Category_score1,Category_cost1] = predict(MFile.KNNStruct_categories,real(File.Features55(1:700,:)));
KNN_Category_Analysis = classperf(File.categories1(1:700,:) ,Category1);
Category_Error_Rate1=KNN_Category_Analysis.ErrorRate;
Category_Accuracy_Rate1=KNN_Category_Analysis.CorrectRate;
Category_SampleDistribution1=KNN_Category_Analysis.SampleDistribution;
Category_ErrorDistribution1=KNN_Category_Analysis.ErrorDistribution;
[Category2,Category_score2,Category_cost2] = predict(MFile.KNNStruct_categories1,File.Features1(1:700,:));
KNN_Category_Analysis = classperf(File.categories1(1:700,:) ,Category2);
Category_Error_Rate2=KNN_Category_Analysis.ErrorRate;
Category_Accuracy_Rate2=KNN_Category_Analysis.CorrectRate;
Category_SampleDistribution2=KNN_Category_Analysis.SampleDistribution;
Category_ErrorDistribution2=KNN_Category_Analysis.ErrorDistribution;
[Category3,Category_score3,Category_cost3] = predict(MFile.KNNStruct_categories2,File.Features2(1:700,:));
KNN_Category_Analysis = classperf(File.categories1(1:700,:) ,Category3);
Category_Error_Rate3=KNN_Category_Analysis.ErrorRate;
Category_Accuracy_Rate3=KNN_Category_Analysis.CorrectRate;
Category_SampleDistribution3=KNN_Category_Analysis.SampleDistribution;
Category_ErrorDistribution3=KNN_Category_Analysis.ErrorDistribution;
[Category4,Category_score4,Category_cost4] = predict(MFile.KNNStruct_categories3,File.Features3(1:700,:));
KNN_Category_Analysis = classperf(File.categories1(1:700,:) ,Category3);
Category_Error_Rate4=KNN_Category_Analysis.ErrorRate;
Category_Accuracy_Rate4=KNN_Category_Analysis.CorrectRate;
Category_SampleDistribution4=KNN_Category_Analysis.SampleDistribution;
Category_ErrorDistribution4=KNN_Category_Analysis.ErrorDistribution;
[Category5,Category_score5,Category_cost5] = predict(MFile.KNNStruct_categories4,File.Features4(1:700,:));
KNN_Category_Analysis = classperf(File.categories1(1:700,:) ,Category3);
Category_Error_Rate5=KNN_Category_Analysis.ErrorRate;
Category_Accuracy_Rate5=KNN_Category_Analysis.CorrectRate;
Category_SampleDistribution5=KNN_Category_Analysis.SampleDistribution;
Category_ErrorDistribution5=KNN_Category_Analysis.ErrorDistribution;
[Category6,Category_score6,Category_cost6] = predict(MFile.KNNStruct_categories5,[real(File.Features55(1:700,:)),File.Features1(1:700,:),File.Features2(1:700,:),File.Features3(1:700,:),File.Features4(1:700,:)]);
KNN_Category_Analysis = classperf(File.categories1(1:700,:) ,Category3);
Category_Error_Rate6=KNN_Category_Analysis.ErrorRate;
Category_Accuracy_Rate6=KNN_Category_Analysis.CorrectRate;
Category_SampleDistribution6=KNN_Category_Analysis.SampleDistribution;
Category_ErrorDistribution6=KNN_Category_Analysis.ErrorDistribution;
Category_Error_Rate=[Category_Error_Rate1,Category_Error_Rate2,Category_Error_Rate3,Category_Error_Rate4,Category_Error_Rate5,Category_Error_Rate6];
Category_Accuracy_Rate=[Category_Accuracy_Rate1,Category_Accuracy_Rate2,Category_Accuracy_Rate3,Category_Accuracy_Rate4,Category_Accuracy_Rate5,Category_Accuracy_Rate6];
%Category=[Category1,Category2,Category3,Category4,Category5,Category6];
%Category_cost=[Category_cost1,Category_cost2,Category_cost3,Category_cost4,Category_cost5];
%Category_SampleDistribution=[Category_SampleDistribution1,Category_SampleDistribution2,Category_SampleDistribution3,Category_SampleDistribution3,Category_SampleDistribution4,Category_SampleDistribution5]
%Category_ErrorDistribution=[Category_ErrorDistribution1,Category_ErrorDistribution2,Category_ErrorDistribution3,Category_ErrorDistribution4,Category_ErrorDistribution5]
%Category_score=[Category_score1,Category_score2,Category_score3,Category_score4,Category_score5];

